version: "3.8"

services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - cassandra:/var/lib/cassandra
    networks:
      - backend

networks:
  backend:

volumes:
  cassandra: